apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: OrderServiceAPI
  description: The OrderServiceAPI API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Swagger OrderAPI
      license:
        name: MIT
    servers:
      - url: http://att.com/orderserviceapi/v1
    paths:
      /order:
        get:
          summary: List all orders
          operationId: listOrders
          tags:
            - orders
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: A paged array of Orders
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/orders"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a Order
          operationId: createOrder
          tags:
            - orders
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /orders/{orderid}:
        get:
          summary: Info for a specific orderid
          operationId: showOrderById
          tags:
            - orderid
          parameters:
            - name: orderid
              in: path
              required: true
              description: The id of the order to retrieve
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/orders"
            default:
              description: unexpected error in get
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        order:
          type: object
          required:
            - orderId
            - channel
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        orders:
          type: array
          items:
            $ref: "#/components/schemas/order"
        Error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
