package droolsexample

import com.test.sampledrools.RuleResponse;
import com.test.sampledrools.Util;
import java.util.Map;

global com.test.sampledrools.Util myUtil;

dialect "java"
rule "CONTACT_DETAIL_EXIST_CHECK"
when
	$ruleResponse:RuleResponse() 
	$orderMap : Map()
			eval(myUtil.checkFieldPresent($orderMap,"response","contactDetail"))
		$newValue : Map() from myUtil.findData($orderMap,"response","contactDetail","order.statusDetail.contactDetail","false")
then
	$ruleResponse.addRuleResponse($newValue);
end