package droolsexample

import com.test.sampledrools.RuleResponse;
import com.test.sampledrools.Util;
import java.util.Map;

global com.test.sampledrools.Util myUtil;

dialect "java"
rule "Rule2"
when
	$ruleResponse:RuleResponse() 
	$orderMap : Map()
	eval(myUtil.checkFieldPresent($orderMap,"request","notes"))
	eval(myUtil.checkFieldPresent($orderMap,"response","requestId"))
	$newValue : Map() from myUtil.findData($orderMap,"request","notes","order.newnotes","false")
then
	$ruleResponse.addRuleResponse($newValue);
end