node {
    	stage('checkout'){
        
        git url: 'https://github.com/prakashg1984/TechPocWorkspace.git'
    
        sh "git rev-parse HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
        println commit_id
        }
    
    dir('springboot-ui'){
        stage('build'){
	        sh "mvn -Dmaven.test.failure.ignore clean install"
	        sh 'docker login --username prakashg84 --password pgPS@0714'
    	}
    	
    	stage('create docker image'){
		        sh 'docker login --username prakashg84 --password pgPS@0714'
		        sh ("docker build -t springboot-ui .")
	            sh ("docker tag  springboot-ui prakashg84/test:springboot-ui")
    	}
    	
    	stage('push docker image'){
			sh ("docker push prakashg84/test:springboot-ui")
    	}
    	
    	stage('create deployment'){
    	    sh 'kubectl delete deployments springboot-ui || true' 
	    sh 'kubectl apply -f deployment.yaml --validate=false'
    	}
    	
    	stage('create service'){
	    sh 'kubectl delete services springboot-uiservice || true'
	    sh 'kubectl apply -f services.yaml --validate=false'
    	}
    }
}
