node {
    docker.withRegistry('https://hub.docker.com/', 'docker-hub-credentials') {
    	def mvnHome
    	
    	stage('checkout'){
        
        mvnHome = tool 'M3'
        git url: 'https://github.com/<user>/workplace.git'
    
        sh "git rev-parse HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
        println commit_id
        }
    
    dir('springboot-elasticsearch-redis'){
        stage('build'){
	        sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean install"
	        sh 'docker login --username <userName> --password <password>'
	        sh ("docker build -t springboot-elasticsearch-redis .")
	        sh ("docker tag  springboot-elasticsearch-redis test:springboot-elasticsearch-redis")
	        sh ("docker push <repo>/test:springboot-elasticsearch-redis")
    	}
    	
    	stage('create docker image'){
		        sh 'docker login --username <user> --password <user>'
		        sh ("docker build -t springboot-elasticsearch-redis .")
		        sh ("docker tag  springboot-elasticsearch-redis <repo>/test:springboot-elasticsearch-redis")
    	}
    	
    	stage('push docker image'){
			sh ("docker push test:springboot-elasticsearch-redis")
    	}
    	
    	stage('create deployment'){
    	    sh 'kubectl delete deployments springboot-elasticsearch-redisapi || true' 
	   		sh 'kubectl create -f deployment.yaml --validate=false'
    	}
    	
    	stage('create service'){
	    	sh 'kubectl delete services springboot-elasticsearch-redisapiservice || true'
	   		sh 'kubectl create -f services.yaml --validate=false'
    	}
    }
    }
}
